name: Deploy to Remote Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Server Access

    steps:
      # Checkout the source code
      - name: Checkout
        uses: actions/checkout@v2

      # Build the Docker Compose file
      - name: Build Docker Compose
        run: |
          docker-compose build

      # Copy the Docker Compose file to server1
      - name: Copy Docker Compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{secrets.PORT}}

          source: ./docker-compose.yml
          target: ./

      # SSH into server1 and then server2 to deploy
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{secrets.PORT}}

          script: |
            ssh -o StrictHostKeyChecking=no -i ${{env.LOCATION}} ${{ env.ASERVER_HOST }} << EOF
              mkdir automationBenekiva
              cd automationBenekiva
              docker-compose build
              # docker-compose up
            EOF
